version: "3" 
services:    
  website: 
    image: php:apache 
    depends_on: 
      - flask
      volumes:
      - ./website:/var/www/html
    ports: 
      - "4000:80" 
    environment: 
       DATABASE_USER: Pozo
       DATABASE_PASSWORD: Pozopass
  flask:
        build: ./simple_api
    volumes: 
      - ./simple_api:/user/scr/app
    ports: 
      - "8000:80" 
